# Generated by Django 5.2.5 on 2025-08-25 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('checkout_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('pending', 'PENDIENTE_PAGO'), ('paid', 'PAGADA'), ('confirmed', 'CONFIRMADA'), ('completed', 'REALIZADA'), ('canceled', 'CANCELADA'), ('refunded', 'REEMBOLSADA')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departure')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tour')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
